# Generated by Django 4.2.6 on 2023-10-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='empresa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stocks',
            field=models.IntegerField(null=True),
        ),
    ]
