# Generated by Django 4.2.6 on 2023-11-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_codes_alter_comment_product_alter_product_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='brand',
            name='marca',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoria',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='codes',
            name='codes',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='empresa',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
