# Generated by Django 4.2.6 on 2023-10-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=200)),
                ('links', models.URLField(null=True)),
                ('codes', models.CharField(max_length=10)),
                ('stocks', models.IntegerField()),
                ('ratings', models.PositiveIntegerField()),
                ('prices_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prices_pen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('images', models.URLField(null=True)),
                ('Fecha', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=10)),
                ('empresa', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=10)),
            ],
        ),
    ]
